# If you only want the circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
  - &filter-only-source
    branches:
      only:
        - source

version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: cimg/node:16.15.0

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "OdedItkinOW@overwolf.com"
            git config --global user.name "Oded Itkin"
            
            cd website && yarn install && GIT_USER=OdedItkinOW CURRENT_BRANCH=source yarn clear && yarn deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-source
